# Nightfox Alacritty Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_alacritty.yml
font:
  size: 16
  normal:
    family: CaskaydiaMono Nerd Font # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: ExtraLight

  # The bold font face
  bold:
    family: CaskaydiaMono Nerd Font  # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italics:
    family: CaskaydiaMono Nerd Font # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Italic

schemes:
  tokyonight: &tokyonight
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    normal:
      black: '#1A1B26'
      blue: '#7AA2F7'
      cyan: '#4ABAAF'
      green: '#9ece6a'
      magenta: '#9A7ECC'
      red: '#ff7a93'
      white: '#ACB0D0'
      yellow: '#E0AF68'

    bright:
      black: "#444b6a"
      blue: '#61AFEF'
      cyan: '#0db9d7'
      green: '#98C379'
      magenta: '#C678DD'
      red: '#E06C75'
      white: '#ABB2BF'
      yellow: '#D19A66'

    indexed_colors:
      - { index: 16, color: '#ff9e64' }
      - { index: 17, color: '#db4b4b' }
  nightfox: &nightfox
    primary:
      background: '0x192330'
      foreground: '0xcdcecf'
    # Normal colors
    normal:
      black:   '0x393b44'
      red:     '0xc94f6d'
      green:   '0x81b29a'
      yellow:  '0xdbc074'
      blue:    '0x719cd6'
      magenta: '0x9d79d6'
      cyan:    '0x63cdcf'
      white:   '0xdfdfe0'
    # Bright colors
    bright:
      black:   '0x575860'
      red:     '0xd16983'
      green:   '0x8ebaa4'
      yellow:  '0xe0c989'
      blue:    '0x86abdc'
      magenta: '0xbaa1e2'
      cyan:    '0x7ad4d6'
      white:   '0xe4e4e5'
    indexed_colors:
      - { index: 16, color: '0xf4a261' }
      - { index: 17, color: '0xd67ad2' }

  dayfox: &dayfox
    # Default colors
    primary:
      background: '0xeaeaea'
      foreground: '0x1d344f'
    # Normal colors
    normal:
      black:   '0x1d344f'
      red:     '0xb95d76'
      green:   '0x618774'
      yellow:  '0xba793e'
      blue:    '0x4d688e'
      magenta: '0x8e6f98'
      cyan:    '0x6ca7bd'
      white:   '0xcdd1d5'
    # Bright colors
    bright:
      black:   '0x24476f'
      red:     '0xc76882'
      green:   '0x629f81'
      yellow:  '0xca884a'
      blue:    '0x4e75aa'
      magenta: '0x9f75ac'
      cyan:    '0x74b2c9'
      white:   '0xcfd6dd'
    indexed_colors:
      - { index: 16, color: '0xe3786c' }
      - { index: 17, color: '0xd685af' }

  dawnfox: &dawnfox
    # Default colors
    primary:
      background: '0xfaf4ed'
      foreground: '0x575279'
    # Normal colors
    normal:
      black:   '0x575279'
      red:     '0xb4637a'
      green:   '0x618774'
      yellow:  '0xea9d34'
      blue:    '0x286983'
      magenta: '0x907aa9'
      cyan:    '0x56949f'
      white:   '0xe5e9f0'
    # Bright colors
    bright:
      black:   '0x5f5695'
      red:     '0xc26d85'
      green:   '0x629f81'
      yellow:  '0xeea846'
      blue:    '0x2d81a3'
      magenta: '0x9a80b9'
      cyan:    '0x5ca7b4'
      white:   '0xe6ebf3'
    indexed_colors:
      - { index: 16, color: '0xd7827e' }
      - { index: 17, color: '0xd685af' }

colors: *tokyonight

cursor:
  style:
    shape: Block
    blinking: Never

draw_bold_text_with_bright_colors: true

key_bindings:
   - { key: Slash,     mods: Control,   chars: "\x1f"                 }
   - { key: Q,         mods: Control,   chars: "\x11"                        }
   - { key: A,         mods: Alt,       chars: "\x1ba"                       }
   - { key: B,         mods: Alt,       chars: "\x1bb"                       }
   - { key: C,         mods: Alt,       chars: "\x1bc"                       }
   - { key: D,         mods: Alt,       chars: "\x1bd"                       }
   - { key: E,         mods: Alt,       chars: "\x1be"                       }
   - { key: F,         mods: Alt,       chars: "\x1bf"                       }
   - { key: G,         mods: Alt,       chars: "\x1bg"                       }
   - { key: H,         mods: Alt,       chars: "\x1bh"                       }
   - { key: I,         mods: Alt,       chars: "\x1bi"                       }
   - { key: J,         mods: Alt,       chars: "\x1bj"                       }
   - { key: K,         mods: Alt,       chars: "\x1bk"                       }
   - { key: L,         mods: Alt,       chars: "\x1bl"                       }
   - { key: M,         mods: Alt,       chars: "\x1bm"                       }
   - { key: N,         mods: Alt,       chars: "\x1bn"                       }
   - { key: O,         mods: Alt,       chars: "\x1bo"                       }
   - { key: P,         mods: Alt,       chars: "\x1bp"                       }
   - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
   - { key: R,         mods: Alt,       chars: "\x1br"                       }
   - { key: S,         mods: Alt,       chars: "\x1bs"                       }
   - { key: T,         mods: Alt,       chars: "\x1bt"                       }
   - { key: U,         mods: Alt,       chars: "\x1bu"                       }
   - { key: V,         mods: Alt,       chars: "\x1bv"                       }
   - { key: W,         mods: Alt,       chars: "\x1bw"                       }
   - { key: X,         mods: Alt,       chars: "\x1bx"                       }
   - { key: Y,         mods: Alt,       chars: "\x1by"                       }
   - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
   - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
   - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
   - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
   - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
   - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
   - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
   - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
   - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
   - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
   - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
   - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
   - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
   - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
   - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
   - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
   - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
   - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
   - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
   - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
   - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
   - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
   - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
   - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
   - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
   - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
   - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
   - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
   - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
   - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
   - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
   - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
   - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
   - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
   - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
   - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
   - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
   - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
   - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
   - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
   - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
   - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
   - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
   - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
   - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
   - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
   - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
   - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
   - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
   - { key: Slash,     mods: Alt,       chars: "\x1b/"                       } # Alt + /  
   - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
   - { key: W,         mods: Command,   chars: "\x1b\x7f"                       }
   - { key: Left,      mods: Alt,       chars: "\x1bb"                       } # one word left
   - { key: Right,     mods: Alt,       chars: "\x1bf"                       } # one word right
   - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
   - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
